# https://hub.docker.com/_/traefik
# https://docs.traefik.io/

version: "3"
services:
  traefik:
    image: traefik:2.1.4
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - DO_AUTH_TOKEN=${DO_API_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA}/traefik.yml:/traefik.yml:ro
      - ${DATA}/acme.json:/acme.json
      - ${DATA}/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      # entrada http para el dominio traefik.DOMAIN y la redireccion a https
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.middlewares=https-redirect@file"
      # entrada https para el dominio traefik.DOMAIN
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN}`)"
      # identificarse
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${USER}:${PASSWORD}"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      # tls
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=doresolver"
      # dashboard de traefik en el puerto 8080
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy: